# Generated by Django 5.1.4 on 2025-01-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cineshelf_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaStream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("summary", models.TextField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StreamPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("description", models.TextField(max_length=150)),
                ("website_url", models.URLField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
    ]
