# Generated by Django 5.1.4 on 2025-01-13 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cineshelf_app", "0002_mediastream_streamplatform_delete_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediastream",
            name="platform",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media_streams",
                to="cineshelf_app.streamplatform",
            ),
            preserve_default=False,
        ),
    ]
